export const AppRoute = {
  // Public — no auth, no app navbar
  landing: "/",
  login: "/login",
  signup: "/signup",
  // Authenticated app
  home: "/home",
  store: "/store",
  storeCart: "/store/cart",
  storeCheckout: "/store/checkout",
  storePayment: "/store/payment",
  storeOrders: "/store/orders",
  music: "/music",
  movies: "/movies",
  moviesWatch: "/movies/watch",
  moviesSearch: "/movies/search",
  moviesWatchlist: "/movies/watchlist",
  moviesPlaylists: "/movies/playlists",
  moviesCategory: "/movies/category",
  anime: "/anime",
  animeWatch: "/anime/watch",
  animeSearch: "/anime/search",
  animeWatchlist: "/anime/watchlist",
  animePlaylists: "/anime/playlists",
  animeCategory: "/anime/category",
  nimrose: "/nimrose",
  cosmos: "/cosmos",
  cosmosSearch: "/cosmos/search",
  cosmosLibrary: "/cosmos/library",
  cosmosSpaceWeather: "/cosmos/space-weather",
  cosmosCompare: "/cosmos/compare",
  cosmosImageLab: "/cosmos/image-lab",
  cosmosOrbitExplorer: "/cosmos/orbit-explorer",
  markets: "/markets",
  marketsAsset: "/markets/asset",
  research: "/research",
  researchDetail: "/research/detail",
  wordpad: "/wordpad",
  customize: "/customize",
  profile: "/profile",
  admin: "/admin",
} as const;
